### ISSUE TITLE
[BUG] crash from cinderBullet damagetype

### ISSUE THREAD

**Issue by schindlershadow** [PickAID/Champions#21]
#### Versions (Be specific, do not write "latest"):
* Champions: champions-neoforge-1.21.1-2.1.8.0-beta.jar
* NeoForge: 21.1.42

#### Observed Behavior:
getting killed by a mob sometimes crashes with this error:

```
java.lang.IllegalArgumentException: Can't find id for 'Direct{DamageType[msgId=cinderBullet, scaling=WHEN_CAUSED_BY_LIVING_NON_PLAYER, exhaustion=0.1, effects=HURT, deathMessageType=DEFAULT]}' in map net.minecraft.core.Registry$1@297db5be
```
#### Expected Behavior:
no crash

Crash Log:
client
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.multiplayer.ClientPacketListener.send(net.minecraft.network.protocol.common.custom.CustomPacketPayload)" because the return value of "net.minecraft.client.Minecraft.getConnection()" is null
```
https://pastebin.com/raw/J12MhTV6

server

latest.log
```
[09Oct2024 10:20:13.469] [Netty Epoll Server IO #1/ERROR] [net.minecraft.network.Connection/]: Exception caught in connection
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:damage_event'
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:55) ~[server-1.21.1-20240808.144430-srg.jar%23382!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:14) ~[server-1.21.1-20240808.144430-srg.jar%23382!/:?]
	at TRANSFORMER/neoforge@21.1.42/net.neoforged.neoforge.network.filters.GenericPacketSplitter.encode(GenericPacketSplitter.java:104) ~[neoforge-21.1.42-universal.jar%23383!/:?]
	at TRANSFORMER/neoforge@21.1.42/net.neoforged.neoforge.network.filters.GenericPacketSplitter.encode(GenericPacketSplitter.java:39) ~[neoforge-21.1.42-universal.jar%23383!/:?]
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar%23104!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar%23104!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection$2.write(Connection.java:528) ~[server-1.21.1-20240808.144430-srg.jar%23382!/:?]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.doSendPacket(Connection.java:364) ~[server-1.21.1-20240808.144430-srg.jar%23382!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.lambda$sendPacket$12(Connection.java:359) ~[server-1.21.1-20240808.144430-srg.jar%23382!/:?]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport.classes.epoll@4.1.97.Final/io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416) ~[netty-transport-classes-epoll-4.1.97.Final.jar%23109!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalArgumentException: Can't find id for 'Direct{DamageType[msgId=cinderBullet, scaling=WHEN_CAUSED_BY_LIVING_NON_PLAYER, exhaustion=0.1, effects=HURT, deathMessageType=DEFAULT]}' in map net.minecraft.core.Registry$1@297db5be
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.core.IdMap.getIdOrThrow(IdMap.java:27) ~[server-1.21.1-20240808.144430-srg.jar%23382!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.ByteBufCodecs$25.encode(ByteBufCodecs.java:479) ~[server-1.21.1-20240808.144430-srg.jar%23382!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.ByteBufCodecs$25.encode(ByteBufCodecs.java:464) ~[server-1.21.1-20240808.144430-srg.jar%23382!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.game.ClientboundDamageEventPacket.write(ClientboundDamageEventPacket.java:57) ~[server-1.21.1-20240808.144430-srg.jar%23382!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$2.encode(StreamCodec.java:42) ~[server-1.21.1-20240808.144430-srg.jar%23382!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:97) ~[server-1.21.1-20240808.144430-srg.jar%23382!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.encode(StreamCodec.java:87) ~[server-1.21.1-20240808.144430-srg.jar%23382!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:53) ~[server-1.21.1-20240808.144430-srg.jar%23382!/:?]
	... 31 more
```
[latest (Copy).log](https://github.com/user-attachments/files/17309904/latest.Copy.log)

**Comment by Hypocisy** [comment]
yes, 1.20.1 also have this bug, i'm trying to figure out how to fix it, you can disable Enkindling affix first, and see if fix this bug.

**Comment by Hypocisy** [comment]
you can check beta-3 here [curseforge](https://www.curseforge.com/minecraft/mc-mods/champions-unofficial/files/5798438)
